### ISSUE TITLE
Script Running: No Data, RTL-SDR

### ISSUE THREAD

**Issue by gudenau** [BitBangingBytes/gr-smart_meters#22]
My local power company is using a `FOCUS AXR-SD` meter and I am unable to capture data from the network.

From what I can tell packets are being sent, at least based on this waterfall.

![image](https://user-images.githubusercontent.com/5642329/178833616-03842d5f-ea0e-4e6a-98be-17fc366f0a69.png)

I followed the instructions as close as possible, with only a couple deviations:
- Skipped `Install Sandia Utilities (Possibly not needed for GR-3.9)`, could not build
- Changed `sample_rate` parameter from `int(2e6)` to `int(2.048e6)` because GNU Radio could not launch it
![Screenshot_2022-07-13_14-54-13](https://user-images.githubusercontent.com/5642329/178833944-d918d194-d1d7-4ba7-9400-f177bcb2bcf4.png)

I did open the `GridStream_RTLSDR_NoGUI.grc` file in GNU Radio. After waiting a while (longer than it takes for several blips on the waterfall in SDR++) all I got in the terminal was this:
![Screenshot_2022-07-13_15-44-09](https://user-images.githubusercontent.com/5642329/178835042-599e8db5-b3af-40a6-8bf5-2d47b7b41031.png)

I also tried running it with the packet ID and length filters of `0x55` and `0x23` respectively.

Terminal output of `gnuradio-companion` appears to be clean:
```
$ gnuradio-companion 
<<< Welcome to GNU Radio Companion 3.9.5.0 >>>

Block paths:
	/usr/share/gnuradio/grc/blocks
	/usr/local/share/gnuradio/grc/blocks

Loading: "/home/gudenau/Desktop/meters/gr-smart_meters/examples/GridStream_RTLSDR_NoGUI.grc"
>>> Done

Generating: '/home/gudenau/Desktop/meters/gr-smart_meters/examples/GridStream_HackRF_NoGUI.py'

Executing: /usr/bin/gnome-terminal -- /usr/bin/python3 -u /home/gudenau/Desktop/meters/gr-smart_meters/examples/GridStream_HackRF_NoGUI.py


>>> Done

Generating: '/home/gudenau/Desktop/meters/gr-smart_meters/examples/GridStream_HackRF_NoGUI.py'

Executing: /usr/bin/gnome-terminal -- /usr/bin/python3 -u /home/gudenau/Desktop/meters/gr-smart_meters/examples/GridStream_HackRF_NoGUI.py


>>> Done

Generating: '/home/gudenau/Desktop/meters/gr-smart_meters/examples/GridStream_HackRF_NoGUI.py'

Executing: /usr/bin/gnome-terminal -- /usr/bin/python3 -u /home/gudenau/Desktop/meters/gr-smart_meters/examples/GridStream_HackRF_NoGUI.py


>>> Done

Generating: '/home/gudenau/Desktop/meters/gr-smart_meters/examples/GridStream_HackRF_NoGUI.py'

Executing: /usr/bin/gnome-terminal -- /usr/bin/python3 -u /home/gudenau/Desktop/meters/gr-smart_meters/examples/GridStream_HackRF_NoGUI.py


>>> Done

Generating: '/home/gudenau/Desktop/meters/gr-smart_meters/examples/GridStream_HackRF_NoGUI.py'

Executing: /usr/bin/gnome-terminal -- /usr/bin/python3 -u /home/gudenau/Desktop/meters/gr-smart_meters/examples/GridStream_HackRF_NoGUI.py


>>> Done
```

I also tried with `PYTHONPATH` set to the `dist-packages` directory with the following output:
```
PYTHONPATH=/usr/local/lib/python3.8/dist-packages/ !!
PYTHONPATH=/usr/local/lib/python3.8/dist-packages/ gnuradio-companion 
<<< Welcome to GNU Radio Companion 3.9.5.0 >>>

Block paths:
	/usr/share/gnuradio/grc/blocks
	/usr/local/share/gnuradio/grc/blocks

Loading: "/home/gudenau/Desktop/meters/gr-smart_meters/examples/GridStream_RTLSDR_NoGUI.grc"
>>> Done

Generating: '/home/gudenau/Desktop/meters/gr-smart_meters/examples/GridStream_HackRF_NoGUI.py'

Executing: /usr/bin/gnome-terminal -- /usr/bin/python3 -u /home/gudenau/Desktop/meters/gr-smart_meters/examples/GridStream_HackRF_NoGUI.py


>>> Done

Generating: '/home/gudenau/Desktop/meters/gr-smart_meters/examples/GridStream_HackRF_NoGUI.py'

Executing: /usr/bin/gnome-terminal -- /usr/bin/python3 -u /home/gudenau/Desktop/meters/gr-smart_meters/examples/GridStream_HackRF_NoGUI.py


>>> Done

Generating: '/home/gudenau/Desktop/meters/gr-smart_meters/examples/GridStream_HackRF_NoGUI.py'

Executing: /usr/bin/gnome-terminal -- /usr/bin/python3 -u /home/gudenau/Desktop/meters/gr-smart_meters/examples/GridStream_HackRF_NoGUI.py


>>> Done
```
with very similar output when running the script.

**Comment by BitBangingBytes** [comment]
It appears you did everything correctly, can you check to see if you have a sticker on the meter that says GridStream?

The Focus AXR-SD meter can have different networking modules, GridStream is one, SilverSpring Networks is another along with even more. This decoder works for Gridstream only, although I have tweaked the sync word to also dump SilverSpring packets in the past but haven't worked hard on decoding those.

**Comment by gudenau** [comment]
Sorry for the massive delay, this is somewhat low on my priority list...

It does have a "Silver Sprint Networks" sticker on it. So I suppose that just isn't supported just yet.

Maybe once I can afford to get a better SDR I'll play around with this some more.
