### ISSUE TITLE
Collection of buglets

### ISSUE THREAD

**Issue by ldoolitt** [BitBangingBytes/gr-smart_meters#23]
For gr-smart_meters itself, and the RECESSIM Gr-smart_meters_Setup_Guide.

My base system is Debian testing (Bookworm) gnuradio 3.10.4.0 and gr-osmosdr 0.2.3.
Maybe a little bleeding-edge at the moment, but it (or something very similar) should go mainstream in a matter of months.
The setup instructions are based on gnuradio 3.8 or 3.9, and don't work as-is on 3.10.  

As discussed in https://lists.gnu.org/archive/html/discuss-gnuradio/2022-12/msg00074.html I needed to
 ```apt-get install --no-install-recommends libsndfile1-dev```
before starting to build the OOT gnuradio modules.
Skipping over gr-osmosdr (because there's a Debian package),

-  gr-pdu_utils
- gr-sandia_utils
- gr-timing_utils
- gr-fhss_utils

all need to have their maint-3.10 branch checked out, and get built and installed in the above order.
I got some compile-time build warnings; logs available on request.

I needed to
``` add apt-get install -y gobject-introspection gir1.2-gtk-3.0```
before gnuradio-companion will start up, otherwise it complained about "Namespace Gtk not available".
I suppose most people wouldn't notice, if they have some default Ubuntu desktop loaded.  I personally find such X environments unusable.  :-(

About gr-smart_meters proper, and examples/GridStream_RTLSDR_NoGUI.grc in particular:

1. It self-identifies as ```id: GridStream_HackRF_NoGUI```.  This leads to it confusingly generating GridStream_HackRF_NoGUI.py when you press gnuradio-companion's Generate button.
2. Running it crashed with an invalid FFT size.  I changed fft_size value: int(2000) to int(1024), and that let it run.

All of this is possibly a waste of my time.  I looked more closely at my electric meter.
I have a California PG&E Landis+Gyr FOCUS AXRe-SD, and the sticker at its top says ITRON, FCC ID: OWS-NIC511-06; no mention of GridStream.

**Comment by BitBangingBytes** [comment]
Thanks! While the GridStream block might not be helpful in decoding your smart meter the whole flow graph may be. If you look at messages output with a Message Debug block prior to the PDU Align block you'll see any transmissions in the ISM band.

You can then determine which messages might be from your meter and set a custom PDU Align value to target them.

As for the other information on installation I have been meaning to update for GR 3.10. The latest dev branch has quite a few changes as well. I also like Conda for installing and managing the environment.

I'll update the wiki soon to make it clearer, thanks a lot for taking the time to document your process.

**Comment by BitBangingBytes** [comment]
Updated the [Wiki Instructions](https://wiki.recessim.com/view/Gr-smart_meters_Setup_Guide), will have to test with a fresh install of Ubuntu to verify.

Dev branch addresses the example flowgraph issues you pointed out. Will push that to main soon, again appreciate your detailed feedback.
