### ISSUE TITLE
Found CRC value

### ISSUE THREAD

**Issue by FreydNot** [BitBangingBytes/gr-smart_meters#33]
South King County, WA | Puget Sound Energy | CRC = 0x142A

Puget Sound Energy (PSE) covers a lot of territory.  I'm not sure if this CRC is used for all of their Washington State infrastructure or just the South King County area.

**Comment by TippyTurtle** [comment]
I can verify Puget Sound Energy (PSE) in Bellevue, WA is also using CRC = 0x142A which is more to the north part of King  county.  I would guess it is all of PSE that uses this CRC. (Found/Calculated it myself before finding this already existing issue.)

**Comment by FreydNot** [comment]
Good to get some verification.

Have you had any luck getting actual data?  I'm having issues, but I assume it's something I've done wrong in my setup.

**Comment by keyboarderror** [comment]
Just thought I'd chime in here. I'm in Olympia in Thurston County, and it seems PSE is also using 0x142A as the CRC here. However I'm not getting anything useful either apparently. I've never gotten anything and I've been trying since GR3.8. But I'm another ear if anyone has anything to suggest.

**Comment by TippyTurtle** [comment]
Same story here; no data success. I haven't been on this really hard lately.
