### ISSUE TITLE
Can't import smart_meters

### ISSUE THREAD

**Issue by floren** [BitBangingBytes/gr-smart_meters#35]
I believe I followed the directions at https://wiki.recessim.com/view/Gr-smart_meters_Setup_Guide correctly on my Debian Testing system. However, if I try to start the rtl sdr flowgraph in gnuradio, or even just try to import `smart_meters` manually from a python repl, I see the following error:

```
>>> import smart_meters
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.11/dist-packages/smart_meters/__init__.py", line 18, in <module>
    from .smart_meters_python import *
ImportError: /usr/local/lib/python3.11/dist-packages/smart_meters/smart_meters_python.cpython-311-x86_64-linux-gnu.so: undefined symbol: _ZN2gr12smart_meters10GridStream4makeEbbbbbbbtjjht
```

I'm afraid my experience with python is limited, so I can't get much further. Any suggestions?

**Comment by BitBangingBytes** [comment]
My guess is something at a fundamental package level is broken. If you can, try using Conda to setup your GNURadio environment. I've had great luck even using this on a new M1 Mac to get gr-smart_meters running.

https://wiki.gnuradio.org/index.php/CondaInstall
