### ISSUE TITLE
Can't decode GPS packets

### ISSUE THREAD

**Issue by keyboarderror** [BitBangingBytes/gr-smart_meters#36]
I have everything set up and seem to be seeing packets with CRC but both generate errors if I enable the GPS decoder blocks. I get the following error twice:

thread_body_wrapper :error: ERROR thread[thread-per-block[10]: <block Google Earth(3)>]: ValueError: invalid literal for int() with base 16: b''

At:
  /usr/local/lib/python3.10/dist-packages/smart_meters/google_earth.py(97): decodeGPS
  /usr/local/lib/python3.10/dist-packages/smart_meters/google_earth.py(68): handle_pdu

thread_body_wrapper :error: ERROR thread[thread-per-block[11]: <block Google Map(2)>]: ValueError: invalid literal for int() with base 16: b''

At:
  /usr/local/lib/python3.10/dist-packages/smart_meters/google_map.py(72): decodeGPS
  /usr/local/lib/python3.10/dist-packages/smart_meters/google_map.py(64): handle_pdu

Just wondering if it's a glitch or something in my settings? I've tried this on two different installations with the same result.

Thanks

**Comment by BitBangingBytes** [comment]
Nice job getting it set up! My instructions aren't clear for how to use the Mapping blocks I think.

You need to make sure CRC checking is set to True, packet type to 0x55 and packet length to 0x23.

This will ensure only good packets containing GPS data are sent to be displayed. This assumes your smart meter network uses GPS data for the WAN address. If they do not, then it won't resolve to a location that makes sense.

You can tell by looking at a 0x55 packet. If you see a meter ID twice in the same packet, the first time preceded by 0xFE then your packets aren't using GPS.

Hope this helps

**Comment by keyboarderror** [comment]
Hello, and thanks for all your effort. OK, this gives me packets with the meter ID twice. They are preceded by 30FFFFFFFFFFFFFE (discarding the first 6 bytes) and the baudrate seems to be only 9600.

The Google Earth and Map blocks don't error anymore but they're producing nonsensical coordinates around the south pole. 

This is on Puget Sound Energy with a CRC of 0x142a. Somehow it doesn't surprise me they'd be different.

I'm listening with a HackRF connected to a discone antenna at 20 feet. There's an impressive number of blips but relatively few decodes. Even fewer with the type/length filters applied. There seems to be other traffic present at various bitrates not necessarily power meter related.

Anyhow, it's been an interesting learning experience following along and I look forward to anything you should discover in future!

**Comment by BitBangingBytes** [comment]
I added your CRC to the main readme, thanks for sharing!
