### ISSUE TITLE
Usage information

### ISSUE THREAD

**Issue by stevecrozz** [BitBangingBytes/gr-smart_meters#37]
I was able to decode some packets in my area (Southern California Edison, Santa Barbara). But I am curious about extracting usage information from these meters. Seems like the only information available is meter id, geo coordinates, uptime, and color. Its super interesting to see this. But is power usage information not part of this system?

**Comment by stevecrozz** [comment]
Thought it might help to include some packets that I captured using your GnuRadio flowgraph using my RTL-SDR:
~~~
30FFFFFFFFFFFF4F017556F120D60C7C5770A0C4807F54560A6D10053827A37E204F91
30FFFFFFFFFFFF4F027556EEC0B003035A8BA0C4807EA3870A30BB056910AB7E20133B
30FFFFFFFFFFFF4F027556EEC03603035CF6A0C4807EA3870AA27B05693D837E307C7B
30FFFFFFFFFFFF4F05CD56D94028001516D2A0848073B6CB0A5E4705AD21E57E2008CF
30FFFFFFFFFFFF4F027556EEC05603035D77A0C4807EA3870A7ADA05692E337E308CD2
30FFFFFFFFFFFF4F027556EEC0B803035E48A0C4807EA3870A005005693E557E20F949
30FFFFFFFFFFFF4F027556EEC0D303035E79A0C4807EA3870A310105690F937E303316
30FFFFFFFFFFFF4F027556EEC0B90303625BA0C4807EA3870A210C05690A617E30882D
30FFFFFFFFFFFF4F05CD56D940C600151C19A0848073B6CB0A628F05AD24E77E30A06E
30FFFFFFFFFFFF4F027556EEC0EE03036461A0C4807EA3870A316A05690FD97E205615
~~~

IV is 2C22

**Comment by BitBangingBytes** [comment]
Thanks for sharing, haven't decoded usage information yet but I added the CRC you included to the main ReadMe file.
