### ISSUE TITLE
Decoder.h Bindings are our of sync

### ISSUE THREAD

**Issue by joshfaust** [BitBangingBytes/gr-smart_meters#39]
You've made a Python CFlag change but did not update something (I've not deep dived it yet but it was in the last 5 months). Changing to commit `f8e869e` has fixed the issue for the time being. 

![image](https://github.com/BitBangingBytes/gr-smart_meters/assets/12776422/c375a66d-671e-4c9e-ae07-0591907d5657)

**Comment by BitBangingBytes** [comment]
Thanks, this issue has been fixed in the 3.10 branch
