### ISSUE TITLE
Question: any interest in a wireshark dissector?

### ISSUE THREAD

**Issue by thebiss** [BitBangingBytes/gr-smart_meters#46]
I'm working on a lua script that Wireshark can use to dissect packets. It doesn't pull usage data from the payload yet, but it appears to pull more headers out of the Oncor file on the wiki. 

It's much easier to review the protocol in Wireshark, where possible fields are labeled. 

Is there any interest in this?

**Comment by BitBangingBytes** [comment]
Definitely!

**Comment by thebiss** [comment]
The repo https://github.com/thebiss/gs-dissector now contains a draft copy, with usage instructions in the README.  Feedback/issues/changes welcome~
