### ISSUE TITLE
Infinite loop in crc16

### ISSUE THREAD

**Issue by robertabcd** [BitBangingBytes/gr-smart_meters#7]
Sometimes I get a bad burst which its length is less than 8. This caused underflow of `out.size()-8` and `crc16()` will not finish. It didn't cause a crash perhaps due to `uint16_t i` wraps around in small range. It's worth putting a check on `out.size()` before calling `crc16()`.

**Comment by BitBangingBytes** [comment]
Thanks! I found the same issue (should have just read your comment first!) and fixed it on the maint-3.9 and master branch. I need to get GR3.8 installed on my system and can push the same change back there and verify.
